chef

Add `--dl_dir` option when using chef init command.
When the option is set, dl-dir json node is added to `.chefConfig`
When the build dir is built, DL_DIR variable is preprended is set in `.chefConfig` file.
Happy review

Add --dl_dir option for chef init command

---

sample-menus/raspberry-pi-cm-3-menu.json

This PR create a sample-menus directory with a first one based on Raspberry Pi Compute Module 3 and u-boot.
Note that the build is done under "warrior" Yocto Project version. It didn't work for me with "zeus".

[DEV] Add a menu for Raspberry Pi CM 3+ and u-boot

---

README.md

According to http://docopt.org/ the positional arguments are better documented
with the syntax `<arg>` than with `{arg}`.

[DOC] Update README.md command line descriptions.

---

chef/chef.py
test/CMakeLists.txt
test/basic/no-subcommand/test

Previous versions of `chef` quit silently when called without sub-command:
```
[~]$ chef
[~]$
```
With this patch an error message is displayed.
```
[~]$ chef
usage: Chef [-h] [--debug] [-v]
{cook,init,update,generate,show,build,clean} ...
Chef: error: the following arguments are required: sub-command
[~]$
```

[DEV] Error message when called without sub-command.

---

chef/chef.py
test/basic/no-subcommand/test

Without argument the `chef` command has to fail with a non-zero exit status.

[FIX] Exit status without argument.

---

README.md

Hello Christophe,
When using the released 1.0.0 chef version, I followed the README to install the tool and ran into some difficulties:
https://github.com/cpb-/chef/blob/master/README.md#installing-chef
With precious help from @Stimaleger  and @pboettch , it is recommended to:
- not use the line `python3 setup.py install`, use pip3 tool instead
- use a different installation if you are a developer or a simple user
On my computer (Ubuntu 16.04 / Python 3.5.2), the current installation procedure with setup.py method doesn't work. Chef installation works apparently well but then, using chef raise the following error:
```
$ chef 
Traceback (most recent call last):
File "/usr/local/bin/chef", line 33, in <module>
sys.exit(load_entry_point('chef==1.0.0', 'console_scripts', 'chef')())
File …
```

Chef installation doc procedure updated

---

chef/chef.py

Hello Christophe, Pat,
Using the brand new 1.0.0 chef version, I had some difficulties to use this tools having the following error:
```
$ chef -v
Traceback (most recent call last):
File "/usr/local/bin/chef", line 33, in <module>
sys.exit(load_entry_point('chef', 'console_scripts', 'chef')())
File "/usr/local/lib/python3.5/dist-packages/chef/chef.py", line 790, in main
ChefCall()
File "/usr/local/lib/python3.5/dist-packages/chef/chef.py", line 689, in __init__
schema = json.loads(pkg_resources.resource_string(__name__, "chef-menu-schema.json"))
File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
and some documentation links to confirm the modification
--> …

json schema ressource must be decoded prior to being loaded as json

---

sample-menus/pi3-sample-menu.json

1. Add a target
2. Fix cmdline erasure. When using the variable CMDLINE, the original command line is erased. Using CMDLINE_append avoids this issue.

Fix pi3 sample menu

---

sample-menus/raspberrypi2-dunfell-menu.json

Hi Christophe & Pat,
Just a simple menu addition for my raspberry pi 2. As dunfell is LTS version, it's even more interesting than any zeus or warrior menus provided in this repo.
Compilation tested under Ubuntu 18.04.
Regards,
Adrien M.

add raspberry pi 2 dunfell menu

---

cooker/cooker.py
test/basic/build/test

bitbake provide the option '-k' or '--continue' to continue as much as
possible after an error.
This is useful for the first build for a new target or after a layer
update when we can expect having some build issues.
Add a new test that check if "-k" is on the bitbake command line if
--keepgoing is used.
Signed-off-by: Romain Naour <romain.naour@gmail.com>

cooker: add --keepgoing option for build command

---

cooker/cooker.py

This ensure that we don't attempt to compile dot-prefixed build (template).

[FIX] Use `buildable()` method to check a build before runnin `bitbake`.

---

cooker/cooker.py

Previously: 
```
$ cooker --help
usage: Cooker [-h] [--debug] [--version] [-v] [-n] {cook,init,update,generate,show,build,shell,clean} ...
[...]
```
After fix: 
```
$ cooker --help
usage: cooker [-h] [--debug] [--version] [-v] [-n] {cook,init,update,generate,show,build,shell,clean} ...
[...]
```

[FIX] `--help` option: program name is `cooker`, not `Cooker`.

---

cooker/cooker-menu-schema.json
cooker/cooker.py
test/basic/generate/multiple-targets.json
test/basic/generate/test
test/basic/inheritance/menu.json
test/basic/inheritance/show-all.ref
test/basic/show/build-output.ref
test/basic/show/conf-output.ref
test/basic/show/fourth-all-output.ref
test/basic/show/layer-output.ref
test/basic/show/menu.json
test/basic/show/tree-output.ref

Enable the build of several targets in the same build directory. The field
'target' in the menu can be a single string or an array of string. If given an
array, all entries will be built (the build order is undefined).
This does not affect the previous 'target' behaviour.

[DEV] Support multiple targets

---

cooker/cooker.py

When the `SHELL` environment variable is not defined, we have
to default to `/bin/bash` (like when we launch `bitbake`) instead
of `/bin/sh` which is often a link to `/bin/dash`.
Closes: #99

[DEV] Default to `bash` when running `cooker shell`.

---

cooker/cooker-menu-schema.json
test/basic/source-types/git-sources.json
test/basic/source-types/test

There are URL which are matching several patterns, this actually OK,
so the schema has to be `anyOf` and not `oneOf` the possible patterns.
fixes #113

urls: fix validation of ambiguous URLs for schema

---

cooker/cooker.py
test/basic/init/test

This PR adds a new option to the `init` command just like `-d/--dl-dir`

Add `-s/--sstate-dir` option to `init` command

---

cooker/cooker.py
test/basic/init/test

When the menu path given in the command init (or cook) started with '/', its absolute path is stored (after symlinks resolution). If not, its path relative to the .cookerconfig is stored (after symlinks resolution).
The aim is to enable to initialize and download the sources in a host machine and build in a container which may have a different location.

[DEV] menu path can be absolute or relative

---

cooker/cooker.py
test/basic/dry-run/output.ref
test/basic/generate/test

The new versions of poky uses `meta-poky/conf/templates/default` instead of `meta-poky/conf` as the path for the template file (Changed in commit [c472d9ba9e970ad4c9bacf7851fcf6245fd03c40](https://git.yoctoproject.org/poky/commit/meta-poky/conf/templates/default/local.conf.sample?id=c472d9ba9e970ad4c9bacf7851fcf6245fd03c40))
This is causing an error and preventing to use yocto-cooker with the new versions of poky.
Issue to resolve: #134

[FIX] Bad path in variable TEMPLATE_CONF in class PokyDistro 

---

cooker/cooker-menu-schema.json
cooker/cooker.py
test/basic/dry-run/override-menu.json
test/basic/dry-run/test
test/basic/init/override-menu-invalid-property.json
test/basic/init/override-menu-unknown-property.json
test/basic/init/test

- Add function to get the overridden distro configuration if it exists
- Add rule in schema to allow to add a new entry in menu
- Add test case for an overridden distro
This is needed for a somewhat exotic setup : When you clone the individual Yocto repo instead of the poky.git combo-layer (Which is easier in order to contribute upstream). In this case the cloned repos can't have the same layout as poky.git.
Note: Ever is the author of the patches, I've reviewed them and will handle the PR from here (Ever has agreed. I hope that's OK)

Add overridden distro configuration for poky

---

sample-menus/beaglebone-zeus-menu.json
sample-menus/lee2-menu.json
sample-menus/meetup-paris-embedded-2022-05-18.json
sample-menus/multiple-inheritances-test.json
sample-menus/qemux86-warrior-menu-short-ssh.json
sample-menus/qemux86-warrior-menu.json
sample-menus/raspberrypi-cm3-warrior-menu.json
sample-menus/raspberrypi2-dunfell-menu.json
sample-menus/raspberrypi2-zeus-menu.json
sample-menus/raspberrypi4-warrior-menu.json
sample-menus/riscv-menu-extrauser.json

Fix an error in the `usermod` command. For some reason it did not fail while the `-P` option did not exist. On recent shadow version, `-P` is for `--prefix` and the build fails.

[FIX] usermod extrauser command

---

README.md
cooker/cooker.py
test/.gitignore
test/basic/shell/output.ref
test/basic/shell/test

PR initially from @amine-smile : https://github.com/cpb-/yocto-cooker/pull/145.
Updated the shell command to support executing a command within the poky-initialized shell. Introduced optional positional arguments, which allows users to specify a command to be executed (similar to what ssh does).  When a command argument is provided, it is executed within the shell environment.
Example: `cooker shell <cooker-build>  'bitbake -c cve_check <package-name>'`
The unittest was added : Only check the generated command line with dry-run. Actually testing that the command run correctly would require cloning a poky environment.
And, also, a minor gitignore improvement.

Add support for executing a command in a poky-initialized shell (v2)

---

cooker/cooker.py
test/basic/dry-run/output.ref
test/basic/generate/one-target-first-bblayers.conf

Tabulation in the BBLAYERS variable can lead to parsing error for some Yocto tools (such as the toast bbclass). Use spaces instead to maintain the readability of the generated bblayers.conf.
Fix #157

fix: replace tabs to four spaces in bblayers.conf
